[project]
name = "oosc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "assemblyai>=0.43.1",
    "dotenv>=0.9.9",
    "pyaudio>=0.2.14",
    "pydub>=0.25.1",
    "spacy>=3.8.7",
    "websocket>=0.2.1",
]
